# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24b64e885546f92ec8c7af53e0b45ef81732a2c6426b2a7d4840b7ff41c466117c39596b7a4b201458e3011a71a591987490eead209c55cac68ca9ca9fcd28b1

test:
  secret_key_base: 76a5ea3d0f7a8a4d2c8cbfae30dbadc6023782fe5ffcc1c2f1c9fdf6033b3f1bc6a6e0bb56fb05d7c26c69a1b53c556b5341c76d428b252ad0bec0490f2a09a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
